{
	"identifiers": [
		"CVE-2013-2191",
		"GHSA-2q4h-27m7-rj67"
	],
	"identifier": "CVE-2013-2191",
	"package_slug": "pypi/python-bugzilla",
	"title": "python-bugzilla has improper validation of X.509 certificates",
	"description": "python-bugzilla before 0.9.0 does not validate X.509 certificates, which allows man-in-the-middle attackers to spoof Bugzilla servers via a crafted certificate.",
	"date": "2024-04-29",
	"pubdate": "2022-05-14",
	"affected_range": "<0.9.0",
	"fixed_versions": [
		"0.9.0"
	],
	"affected_versions": "All versions before 0.9.0",
	"not_impacted": "All versions starting from 0.9.0",
	"solution": "Upgrade to version 0.9.0 or above.",
	"urls": [
		"https://nvd.nist.gov/vuln/detail/CVE-2013-2191",
		"https://github.com/advisories/GHSA-2q4h-27m7-rj67",
		"https://github.com/python-bugzilla/python-bugzilla/commit/a782282ee479ba4cc1b8b1d89700ac630ba83eef",
		"https://bugzilla.redhat.com/show_bug.cgi?id=951594",
		"https://git.fedorahosted.org/cgit/python-bugzilla.git/commit/?id=a782282ee479ba4cc1b8b1d89700ac630ba83eef",
		"https://github.com/python-bugzilla/python-bugzilla",
		"https://lists.fedorahosted.org/pipermail/python-bugzilla/2013-June/000104.html"
	],
	"cwe_ids": [
		"CWE-20",
		"CWE-937",
		"CWE-1035"
	],
	"uuid": "24904ab5-b5b7-4e6f-90a7-ff3bf19b51cd",
	"cvss_v2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
}
